### ISSUE TITLE
Fix title

### ISSUE THREAD

**Issue by btk5h** [ucsb-cs156-w21/proj-mapache-search#107]
# User Story

As a user I can see the correct app name from the tab, so I don't have to click on the tab to know what the webpage is.

# Acceptance Criteria

- [x] The tab displays the title "Mapache Search", no matter what page the user navigates to

# Discussion

In the file `javascript/public/index.html` we find this code:

```html
 <title>Demo CRA + Spring App</title>
```

By changing that to 

```html
 <title>Mapache Search</title>
```

we can make it so that this text appears on the browser tab when this page is loaded.  This will affect every page in the app. 

# Implementation Todos

Front end:

- [x] The title for the main index page (filename: `javascript/public/index.html` should be updated to the proper name

Testing:

- [x] No automated test for this change is needed. (The change is in a static `index.html` file, not in Java or JavaScript code, and we don't currently have any test infrastucture in place to test for items in the `<head>` section of the static `index.html` file of the app.)
- [x] All previous tests still pass

# Implementation Details: 

Students can follow example in this PR: https://github.com/ucsb-cs156-w21/demo-spring-react-minimal/pull/7

**Comment by avatarmiko** [comment]
Branch: 6pm-2-fix-title
