### ISSUE TITLE
Write more descriptive NavBar titles for the two different searches to articulate the purpose of each.

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-mapache-search#110]
# User Story

As a user, I should be able to read and understand the titles of the two different search options so I can choose the right one.

# Discussion

More useful titles will probably be a bit longer and will let users know exactly what search they will see when the click on the tab. For instance, the first Search tab searches messages in the Slack, whereas the second searches Google.

# Acceptance Criteria
- [x] The "Search" with a dropdown should be renamed "Slack Search" and the "Search"  without a dropdown should be renamed "Google Search".

# Implementation Hints
- Changes should be to the file `javascript/src/main/components/Nav/AppNavbar.js`.
# Testing Hints
- A new test should be added to `proj-mapache-search/javascript/src/test/components/Nav/AppNavbar.test.js` for _each_ modified navbar link, which checks that the new navbar text is correctly displayed. It should look something like the following:
```
test("TEST_NAME", () => {
    const history = createMemoryHistory();
    const { getByText } = render(
      <Router history={history}>
        <AppNavbar />
      </Router>
    );

    const userInfoLink = getByText(/[NEW_TITLE]/);
    expect(userInfoLink.href).toMatch([CORRECT_LINK_TO_SEARCH_PAGE]);
  });
```

**Comment by pconrad** [comment]
* The `Search` menu option that links to `https://proj-mapache-search.herokuapp.com/member/search` can be renamed `Google Search`

**Comment by pconrad** [comment]
Rename `Analyze Message Data` to `Analyze Slack Data`

**Comment by kaiwenli1** [comment]
Branch: 7pm-2-editSearchTitleName
