### ISSUE TITLE
Google Search Results are in JSON... reformat so that they are legible

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-mapache-search#130]
# User Story

As a user of the `/mapache` slack slash command, I can do `/mapache search google foobar` and get back nicely formatted search results (instead of just a dump of the JSON of the search results).

# Discussion

Currently `/mapache search google spring boot` will result in a dump of search results in JSON format.  Instead, we should use the fields in the results (using the `title` field (though probably use the `htmlTitle` field to display), the `htmlSnippet`, and the `htmlFormattedUrl` should link to the actual `url`).

(You can try this on the course slack)

# Acceptance Criteria

- [ ] A `/mapache search google spring boot` command gives back usable search results in some pleasing format

**Comment by BaldPulse** [comment]
Refactored into @163 and @166.
