### ISSUE TITLE
Fix day/time stamps in members/channels/annoucements

### ISSUE THREAD

**Issue by vivianross06** [ucsb-cs156-w21/proj-mapache-search#152]
In member/channels/announcements, the day/time stamps seems to be incorrect.   See if this is a bug, and if so fix it.

# User Story

* As a member 
* I can see the correct date and time a message was sent
* So that I can more easily match a message to its source in a Slack channel.

Before: 

<img width="1221" alt="Screen Shot 2021-03-02 at 12 07 05 PM" src="https://user-images.githubusercontent.com/49248018/109708137-de787080-7b4f-11eb-918b-7120dfa0259e.png">

After:

The date should be correct (e.g. 2021-01-11 14:13:09)

# Acceptance Criteria

- [x] On channel message page, every date should be formatted correctly.
...

# Implementation Todos

Getting Started:

- [x] Identify the component displaying the date and time
- [x] Look for/identify bug causing incorrect date to appear
- [x] Fix bug and display the correct date and time

Testing:

- [x] All tests pass and there is adequate coverage

**Comment by jayleenli** [comment]
Adding a comment I think this bug is actually affecting all channels, but I'm pretty sure if you are changing the component it should change all the other channels
