### ISSUE TITLE
Make the `/admin/searchedTerms` page actually display data from the database

### ISSUE THREAD

**Issue by phtcon** [ucsb-cs156-w21/proj-mapache-search#193]
# User Story

As a user I can bring up the table of searched terms so that I can see all of the terms that were searched and how often.

# Discussion

The data shown at this point will still be fake data, since the story to update the table with real data is still in progress.

You can use the file `data.sql.SAMPLE` to put in SQL commands that will populate the table.   When you copy that file to `data.sql` (temporarily), then on localhost that data will be put into the table for testing.

Do not commit data.sql to the repo; only data.sql.SAMPLE.

# Acceptance Criteria

- [ ] There is a data.sql.SAMPLE that can be used to populate the searched terms table.
- [ ] On localhost, when `data.sql `is used to populate that table, we can see that data when we bring up the searched terms table on the front end route `/admin/searchedTerms`

# Implementation Todos

Back end:

- [ ] Rename Search entity and repository to SearchedTerm entity and SearchedTermRepository to avoid confusion (the word "Search" is already being used in an existing controller.
- [ ] Add a SearchedTermsController that has a method in it to list all of the contents of the SearchedTerms table, on the route `/api/member/searchedterms`

Front End:

- [ ] Add code to the page `javascript/src/main/pages/Admin/SearchedTerms.js` to fetch data from that api and display it in the table

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

**Comment by pconrad** [comment]
This is now a duplicate so closing
