### ISSUE TITLE
Histogram of Messages for a user over time

### ISSUE THREAD

**Issue by neenbeannnn** [ucsb-cs156-w21/proj-mapache-search#30]
# User Story
As a member/admin I can see user-specific level of activity histogram (by week) so that I can see when certain people are online and their participation in the course

# Acceptance Criteria

- [ ] Ability to select a user and view their activity histogram
- [ ] Activity histogram has y axis of time, x axis of message count 
- [ ] Consistent scale of message count for all users

# Implementation Todos

Front end:

- [ ] Create React Component that can be added to a user's profile to display the histogram
- [ ] Use backend message data to populate the histogram, specific to each user (dependent on unique user id)
- [ ] Determine a consistent scale to uniformly use across the histograms

Back end:

- [ ] Connect to the database and retrieve the message count, separated and sorted by day

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

**Comment by pconrad** [comment]
Closing, rolled over to: https://github.com/ucsb-cs156-w21/proj-mapache-search/issues/136
