### ISSUE TITLE
Users can add their google search api to their accounts

### ISSUE THREAD

**Issue by soohyunchoi** [ucsb-cs156-w21/proj-mapache-search#37]
# User Story

As a user I can add a custom google search api token to my account, so that I can enable searching from within the mapache search app for up to 100 searches per user per day.

# Acceptance Criteria

- [ ] Each user will be able to submit up to 100 searches per day
- [ ] Each user will be able to associate a custom google search api token with their unique account

# Implementation Todos

Front end:
- [x] Implement a field to input a custom google search api token
- [ ] Display error message for invalid token

Back end:
- [ ] Create variable/object to store unique custom google search api tokens with each account
- [ ] Modify MongoDB objects in order to account for extra api token field
- [ ] Store variable/object in MongoDB for each account
- [ ] Implement tests and error message for invalid token

**Comment by pconrad** [comment]
Rolled over to issue #135 in W21
